# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'Docker HUB'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker HUB'
    repository: 'pavcg/catalog-api'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'